### ISSUE TITLE
Settings not saved on new server

### ISSUE THREAD

**Issue by davralin** [vranki/hemppa#112]
Hemppa, and synapse running on kubernetes, with haproxy in front.
Completely new installation of synapse/matrix, but I used hemppa against my older installation without issues.
Only thing I can think of, is that this is a version six-room.

    2020-11-18 11:01:29,550 - INFO - hemppa - enabled debugging
    2020-11-18 11:01:29,550 - DEBUG - hemppa - Logger initialized
    2020-11-18 11:01:29,551 - INFO - hemppa - load module: help
    2020-11-18 11:01:29,557 - INFO - hemppa - load module: ig
    2020-11-18 11:01:29,630 - INFO - hemppa - load module: apod
    2020-11-18 11:01:29,635 - INFO - hemppa - load module: wa
    2020-11-18 11:01:29,665 - INFO - hemppa - load module: jitsi
    2020-11-18 11:01:29,668 - INFO - hemppa - load module: welcome_server
    2020-11-18 11:01:29,671 - INFO - hemppa - load module: teamup
    2020-11-18 11:01:30,327 - INFO - hemppa - load module: loc
    2020-11-18 11:01:30,376 - INFO - hemppa - load module: flog
    2020-11-18 11:01:30,382 - INFO - hemppa - load module: echo
    2020-11-18 11:01:30,384 - INFO - hemppa - load module: room
    2020-11-18 11:01:30,388 - INFO - hemppa - load module: notam
    2020-11-18 11:01:30,390 - INFO - hemppa - load module: mxma
    2020-11-18 11:01:30,392 - INFO - hemppa - load module: md
    2020-11-18 11:01:30,556 - INFO - hemppa - load module: metar
    2020-11-18 11:01:30,559 - INFO - hemppa - load module: cmd
    2020-11-18 11:01:30,562 - INFO - hemppa - load module: welcome_room
    2020-11-18 11:01:30,566 - INFO - hemppa - load module: url
    2020-11-18 11:01:30,902 - INFO - hemppa - load module: relay
    2020-11-18 11:01:30,906 - INFO - hemppa - load module: googlecal
    2020-11-18 11:01:31,488 - INFO - hemppa - load module: cron
    2020-11-18 11:01:31,492 - INFO - hemppa - load module: bot
    2020-11-18 11:01:31,497 - INFO - hemppa - load module: taf
    2020-11-18 11:01:31,655 - INFO - hemppa - Bot is on 'Instagram'(!wzoYHTVkALQNJJzCgz:MATRIX.SERVER) with 2 users
    2020-11-18 11:01:31,721 - ERROR - hemppa - Getting account data failed: <Response [403]> {'errcode': 'M_FORBIDDEN', 'error': 'Cannot get account data for other users.'} - this is normal if you have not saved any settings yet.
    2020-11-18 11:01:31,722 - INFO - hemppa - Starting 16 modules..
    2020-11-18 11:01:31,722 - INFO - module help - Starting..
    2020-11-18 11:01:31,722 - INFO - module apod - Starting..
    2020-11-18 11:01:31,722 - INFO - module wa - Starting..
    2020-11-18 11:01:31,722 - INFO - module jitsi - Starting..
    2020-11-18 11:01:31,722 - INFO - module teamup - Starting..
    2020-11-18 11:01:31,722 - INFO - module loc - Starting..
    2020-11-18 11:01:31,722 - INFO - module echo - Starting..
    2020-11-18 11:01:31,723 - INFO - module room - Starting..
    2020-11-18 11:01:31,723 - INFO - module notam - Starting..
    2020-11-18 11:01:31,723 - INFO - module mxma - Starting..
    2020-11-18 11:01:31,723 - INFO - module md - Starting..
    2020-11-18 11:01:31,723 - INFO - module metar - Starting..
    2020-11-18 11:01:31,723 - INFO - module relay - Starting..
    2020-11-18 11:01:31,723 - INFO - module cron - Starting..
    2020-11-18 11:01:31,723 - INFO - module bot - Starting..
    2020-11-18 11:01:31,724 - INFO - module taf - Starting..
    2020-11-18 11:01:31,778 - ERROR - hemppa - Getting account data failed: <Response [403]> {'errcode': 'M_FORBIDDEN', 'error': 'Cannot get account data for other users.'} - this is normal if you have not saved any settings yet.
    2020-11-18 11:01:31,779 - INFO - hemppa - Note: Bot will join rooms if invited
    2020-11-18 11:01:31,779 - INFO - hemppa - Bot running as hemppa, owners ['@USER:MATRIX.SERVER]
    2020-11-18 11:34:29,544 - INFO - module bot - asked to enable ig
    2020-11-18 11:34:29,544 - INFO - module ig - Starting..
    2020-11-18 11:34:29,609 - ERROR - hemppa - Setting account data failed. response: <Response [403]> json: {'errcode': 'M_FORBIDDEN', 'error': 'Cannot add account data for other users.'}
    2020-11-18 11:34:33,628 - INFO - module bot - asked to disable cron
    2020-11-18 11:34:33,628 - INFO - module cron - Stopping..
    2020-11-18 11:34:33,694 - ERROR - hemppa - Setting account data failed. response: <Response [403]> json: {'errcode': 'M_FORBIDDEN', 'error': 'Cannot add account data for other users.'}
    2020-11-18 11:35:05,286 - INFO - module ig - Adding Instagram account sonataarcticaofficial to room id !wzoYHTVkALQNJJzCgz:MATRIX.SERVER
    2020-11-18 11:35:05,341 - ERROR - hemppa - Setting account data failed. response: <Response [403]> json: {'errcode': 'M_FORBIDDEN', 'error': 'Cannot add account data for other users.'}
    2020-11-18 11:35:12,942 - DEBUG - module ig - Polling all accounts for room !wzoYHTVkALQNJJzCgz:MATRIX.SERVER - but this is first sync so I wont send messages
    2020-11-18 11:35:13,557 - ERROR - module ig - Polling instagram account failed:
    Traceback (most recent call last):
    File "/bot/modules/ig.py", line 22, in poll_implementation
        medias = self.instagram.get_medias(account, 5)
    File "/usr/local/lib/python3.7/site-packages/igramscraper/instagram.py", line 288, in get_medias
        account = self.get_account(username)
    File "/usr/local/lib/python3.7/site-packages/igramscraper/instagram.py", line 1127, in get_account
        if user_array['entry_data']['ProfilePage'][0]['graphql']['user'] is None:
    KeyError: 'ProfilePage'
    2020-11-18 11:35:33,292 - INFO - hemppa - Received signal SIGTERM
    2020-11-18 11:35:33,297 - INFO - hemppa - Stopping 23 modules..
    2020-11-18 11:35:33,297 - INFO - module help - Stopping..
    2020-11-18 11:35:33,297 - INFO - module ig - Stopping..
    2020-11-18 11:35:33,297 - INFO - module apod - Stopping..
    2020-11-18 11:35:33,297 - INFO - module wa - Stopping..
    2020-11-18 11:35:33,297 - INFO - module jitsi - Stopping..
    2020-11-18 11:35:33,297 - INFO - hemppa - remove callback
    2020-11-18 11:35:33,298 - INFO - module welcome_server - Stopping..
    2020-11-18 11:35:33,298 - INFO - module teamup - Stopping..
    2020-11-18 11:35:33,298 - INFO - module loc - Stopping..
    2020-11-18 11:35:33,298 - INFO - hemppa - remove callback
    2020-11-18 11:35:33,298 - INFO - module flog - Stopping..
    2020-11-18 11:35:33,298 - INFO - module echo - Stopping..
    2020-11-18 11:35:33,298 - INFO - module room - Stopping..
    2020-11-18 11:35:33,298 - INFO - module notam - Stopping..
    2020-11-18 11:35:33,298 - INFO - module mxma - Stopping..
    2020-11-18 11:35:33,298 - INFO - module md - Stopping..
    2020-11-18 11:35:33,298 - INFO - module metar - Stopping..
    2020-11-18 11:35:33,299 - INFO - module cmd - Stopping..
    2020-11-18 11:35:33,299 - INFO - module welcome_room - Stopping..
    2020-11-18 11:35:33,299 - INFO - module url - Stopping..
    2020-11-18 11:35:33,299 - INFO - module relay - Stopping..
    2020-11-18 11:35:33,299 - INFO - hemppa - remove callback
    2020-11-18 11:35:33,299 - INFO - module googlecal - Stopping..
    2020-11-18 11:35:33,299 - INFO - module cron - Stopping..
    2020-11-18 11:35:33,299 - INFO - module bot - Stopping..
    2020-11-18 11:35:33,299 - INFO - module taf - Stopping..
    2020-11-18 11:35:33,300 - INFO - hemppa - Connection closed

Second run, after I killed the pod/container:

    2020-11-18 11:35:38,290 - INFO - hemppa - enabled debugging
    2020-11-18 11:35:38,291 - DEBUG - hemppa - Logger initialized
    2020-11-18 11:35:38,292 - INFO - hemppa - load module: help
    2020-11-18 11:35:38,299 - INFO - hemppa - load module: ig
    2020-11-18 11:35:38,379 - INFO - hemppa - load module: apod
    2020-11-18 11:35:38,385 - INFO - hemppa - load module: wa
    2020-11-18 11:35:38,420 - INFO - hemppa - load module: jitsi
    2020-11-18 11:35:38,423 - INFO - hemppa - load module: welcome_server
    2020-11-18 11:35:38,426 - INFO - hemppa - load module: teamup
    2020-11-18 11:35:39,106 - INFO - hemppa - load module: loc
    2020-11-18 11:35:39,146 - INFO - hemppa - load module: flog
    2020-11-18 11:35:39,151 - INFO - hemppa - load module: echo
    2020-11-18 11:35:39,153 - INFO - hemppa - load module: room
    2020-11-18 11:35:39,157 - INFO - hemppa - load module: notam
    2020-11-18 11:35:39,159 - INFO - hemppa - load module: mxma
    2020-11-18 11:35:39,162 - INFO - hemppa - load module: md
    2020-11-18 11:35:39,330 - INFO - hemppa - load module: metar
    2020-11-18 11:35:39,332 - INFO - hemppa - load module: cmd
    2020-11-18 11:35:39,336 - INFO - hemppa - load module: welcome_room
    2020-11-18 11:35:39,339 - INFO - hemppa - load module: url
    2020-11-18 11:35:39,676 - INFO - hemppa - load module: relay
    2020-11-18 11:35:39,680 - INFO - hemppa - load module: googlecal
    2020-11-18 11:35:40,209 - INFO - hemppa - load module: cron
    2020-11-18 11:35:40,212 - INFO - hemppa - load module: bot
    2020-11-18 11:35:40,217 - INFO - hemppa - load module: taf
    2020-11-18 11:35:40,354 - INFO - hemppa - Bot is on 'Instagram'(!wzoYHTVkALQNJJzCgz:MATRIX.SERVER) with 2 users
    2020-11-18 11:35:40,410 - ERROR - hemppa - Getting account data failed: <Response [403]> {'errcode': 'M_FORBIDDEN', 'error': 'Cannot get account data for other users.'} - this is normal if you have not saved any settings yet.
    2020-11-18 11:35:40,411 - INFO - hemppa - Starting 16 modules..
    2020-11-18 11:35:40,411 - INFO - module help - Starting..
    2020-11-18 11:35:40,411 - INFO - module apod - Starting..
    2020-11-18 11:35:40,412 - INFO - module wa - Starting..
    2020-11-18 11:35:40,412 - INFO - module jitsi - Starting..
    2020-11-18 11:35:40,412 - INFO - module teamup - Starting..
    2020-11-18 11:35:40,412 - INFO - module loc - Starting..
    2020-11-18 11:35:40,412 - INFO - module echo - Starting..
    2020-11-18 11:35:40,413 - INFO - module room - Starting..
    2020-11-18 11:35:40,413 - INFO - module notam - Starting..
    2020-11-18 11:35:40,413 - INFO - module mxma - Starting..
    2020-11-18 11:35:40,413 - INFO - module md - Starting..
    2020-11-18 11:35:40,413 - INFO - module metar - Starting..
    2020-11-18 11:35:40,413 - INFO - module relay - Starting..
    2020-11-18 11:35:40,413 - INFO - module cron - Starting..
    2020-11-18 11:35:40,414 - INFO - module bot - Starting..
    2020-11-18 11:35:40,414 - INFO - module taf - Starting..
    2020-11-18 11:35:40,484 - ERROR - hemppa - Getting account data failed: <Response [403]> {'errcode': 'M_FORBIDDEN', 'error': 'Cannot get account data for other users.'} - this is normal if you have not saved any settings yet.
    2020-11-18 11:35:40,484 - INFO - hemppa - Note: Bot will join rooms if invited
    2020-11-18 11:35:40,484 - INFO - hemppa - Bot running as hemppa, owners ['@USER:MATRIX.SERVER']

**Comment by davralin** [comment]
Just had the unfortunate opportunity to retry this on a completely wiped database, same issue again - so this should be reproducible on a new server too.

Just for the fun of it, I also tried it in the repo's own room, which is version 5. Same issue there.

**Comment by davralin** [comment]
... nor with an admin-account.

**Comment by vranki** [comment]
Could you confirm you have actually saved any bot settings by using some module that actually stores account data? As the error message says, it's normal if there is no account data saved. Can you also find any bot account data if you login to the account with element web and use /devtools command? Do commands that save account data print any error to log?

**Comment by xPMo** [comment]
I had a 403 issue, and the issue was because I needed to provide the fully-qualified username. `MATRIX_USER=@botname` caused this error, but `MATRIX_USER=@botname:$homeserver` did not.

**Comment by vranki** [comment]
MATRIX_USER is full MXID, not just username, so works as documented.
