### ISSUE TITLE
Welcome Server module error

### ISSUE THREAD

**Issue by Rambonit** [vranki/hemppa#155]
Hi getting this error when enabled the welcome server module. (running in docker)

 Traceback (most recent call last):
   File "./bot.py", line 467, in poll_timer
     await moduleobject.matrix_poll(self, self.pollcount)
   File "/bot/modules/welcome_server.py", line 54, in matrix_poll
     server_user_delta = self.get_server_user_delta(bot)
   File "/bot/modules/welcome_server.py", line 115, in get_server_user_delta
     user_list = self.get_server_user_list()
   File "/bot/modules/welcome_server.py", line 127, in get_server_user_list
     self.welcome_settings["user_query_host"] + "/_synapse/admin/v2/users",
 KeyError: 'user_query_host'

I tried replacing the variable by the url and got another error:

 Traceback (most recent call last):
   File "./bot.py", line 467, in poll_timer
     await moduleobject.matrix_poll(self, self.pollcount)
   File "/bot/modules/welcome_server.py", line 64, in matrix_poll
     server_user_delta = self.get_server_user_delta(bot)
   File "/bot/modules/welcome_server.py", line 128, in get_server_user_delta
     self.welcome_settings["last_server_users"]
 KeyError: 'last_server_users'

**Comment by xPMo** [comment]
The lookup will fail until you `!welcome_server welcome_message Your welcome message here`.

**Comment by VardanAggarwal** [comment]
> The lookup will fail until you `!welcome_server welcome_message Your welcome message here`.

But the lookup is failing in above command only.

**Comment by xPMo** [comment]
> But the lookup is failing in above command only.

It doesn't fail when running `!welcome_server` at all, just when `matrix_poll` detects new users when no message has been configured.  This could be fixed if hemppa adds a basic template message when no message is returned from account data.
