### ISSUE TITLE
Flog: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#160]
Not sure what's happening. System running out of sockets? Who is leaking them?

https://stackoverflow.com/questions/11981933/python-urllib2-cannot-assign-requested-address

```
Traceback (most recent call last):
  File "./bot.py", line 467, in poll_timer
    await moduleobject.matrix_poll(self, self.pollcount)
  File "/bot/modules/flog.py", line 95, in matrix_poll
    await self.poll_implementation(bot)
  File "/bot/modules/flog.py", line 100, in poll_implementation
    data = self.fb.get_flights(station)
  File "/bot/modules/flog.py", line 25, in get_flights
    response = urllib.request.urlopen(self.base_url + "/logbook/" + icao)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

```

**Comment by vranki** [comment]
Rebooting server didn't help. Something has changed somewhere.
