### ISSUE TITLE
!help throws AttributeError: 'MatrixModule' object has no attribute 'info'

### ISSUE THREAD

**Issue by matthijskooijman** [vranki/hemppa#175]
I just cloned the latest git master (cc65d630a0fb0536322d6fb83fa48a9634e50c04) and ran it in docker, which seems to work. However, the `!help` command seems to be broken. The log says:

```
hemppa-matrix-bot | 2021-10-07 01:21:43,792 - ERROR - hemppa - unhandled exception in !help                                                                   
hemppa-matrix-bot | Traceback (most recent call last):
hemppa-matrix-bot |   File "/bot/bot.py", line 444, in message_cb
hemppa-matrix-bot |     await moduleobject.matrix_message(self, room, event)
hemppa-matrix-bot |   File "/bot/modules/help.py", line 69, in matrix_message
hemppa-matrix-bot |     msg = msg + '\n' + self.info
hemppa-matrix-bot | AttributeError: 'MatrixModule' object has no attribute 'info'  
```

**Comment by ellidi** [comment]
> Issue should resolve itself, after a restart of the Bot.

I have this issue as well, bot restart doesn't help. Any ideas?

**Comment by zikapanam** [comment]
Hello,

I'm totally new to hemppa. I ran into the same issue.

Someone can tell me how to write settings ?

The command "!bot export" give me an error.

`  | Traceback (most recent call last):
hemppa    |   File "./bot.py", line 444, in message_cb
hemppa    |     await moduleobject.matrix_message(self, room, event)
hemppa    |   File "/bot/modules/bot.py", line 57, in matrix_message
hemppa    |     await self.export_settings(bot, event)
hemppa    |   File "/bot/modules/bot.py", line 221, in export_settings
hemppa    |     data = bot.get_account_data()['module_settings']
hemppa    | TypeError: 'NoneType' object is not subscriptable
`
Thx for your help !
