### ISSUE TITLE
Issue with !apod

### ISSUE THREAD

**Issue by ptman** [vranki/hemppa#195]
```
ERROR - hemppa - unable to upload file. msg: Request must specify a Content-Length 
ERROR - hemppa - unhandled exception in !apod
Traceback (most recent call last):
  File "/bot/modules/apod.py", line 103, in send_apod
    matrix_uri, mimetype, w, h, size = bot.get_uri_cache(apod.hdurl)
TypeError: cannot unpack non-iterable NoneType object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/bot/modules/apod.py", line 107, in send_apod
    matrix_uri, mimetype, w, h, size = await bot.upload_image(apod.hdurl)
  File "/bot/bot.py", line 178, in upload_image
    raise UploadFailed
bot.UploadFailed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/bot/bot.py", line 445, in message_cb
    await moduleobject.matrix_message(self, room, event)
  File "/bot/modules/apod.py", line 53, in matrix_message
    await self.send_apod(bot, room, self.apod_api_url)
  File "/bot/modules/apod.py", line 109, in send_apod
    await self.send_text(room, f"Something went wrong uploading {apod.hdurl}.")
AttributeError: 'MatrixModule' object has no attribute 'send_text'
```

Bot is running in docker, image built with `docker build` . Other commands seem to work (like `!help`, `!echo`)

**Comment by xPMo** [comment]
Two issues:

- intermittent failure in uploading the pic of the day to the homeserver, I don't think that's a hemppa issue (although maybe we could make hemppa more persistent/patient? Probably not.)
- copy-paste bug using `self.send_text` instead of `bot.send_text`. I'll push a fix for that.
